cyber_range_dir: /home/ubuntu/cyris/cyber_range
cyris_path: /home/ubuntu/cyris
gw_account: null
gw_inside_addr: null
gw_mgmt_addr: null
gw_mode: false
user_email: null

# Storage directories for VM images and builds
build_storage_dir: ./images/builds
vm_storage_dir: ./images/vms
