---
- host_settings:
  - id: host_1
    mgmt_addr: localhost
    virbr_addr: 192.168.122.1
    account: ubuntu

- guest_settings:
  - id: desktop
    basevm_host: host_1
    basevm_config_file: /home/ubuntu/cyris/images/basevm.xml
    basevm_type: kvm

- clone_settings:
  - range_id: basic
    hosts:
    - host_id: host_1
      instance_number: 1
      guests:
      - guest_id: desktop
        number: 1
        entry_point: yes
      topology:
      - type: custom
        networks:
        - name: office
          members: desktop.eth0
